var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},h),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=h.print||console.log.bind(console),m=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);var ma=h.wasmBinary,na,p=!1,oa,r,u,pa,ra,v,w,x,y,ka=a=>a.startsWith("file://"),sa;
function ta(a,b){function c(){var n=0,q=0;do{var t=f[e++];n+=(t&127)<<q;q+=7}while(t&128);return n}function d(){var n=c();c();0!=(n&1)&&c()}var e=8,g=0;this.ac={};this.fc=[];this.hc={};var f=a;a:for(;e<f.length;){a=f[e++];var l=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,f[e++]){case 0:++g;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)l=c(),this.ac[g++]=e,this.fc.push(e),e+=l;break a}e=l}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(f=new Uint8Array(b),e=0;e<f.length;)if(b=f[e++],g=c(),1!=b)e+=g;else for(a=c();0<a--;)b=c(),g=c(),this.hc[b]=z(f,e,g),e+=g}var A=0,B=null;function ua(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==va&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a),d=await WebAssembly.instantiate(c,b);sa=new ta(c,d.module);return d}catch(e){m(`failed to asynchronously prepare wasm: ${e}`),ua(e)}}
async function ya(a){var b=va;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"}),d=(await c).clone(),e=await WebAssembly.instantiateStreaming(c,a),g=await d.arrayBuffer();try{sa=new ta(new Uint8Array(g),e.module)}catch(f){m(`failed to initialize offset-converter: ${f}`)}return e}catch(f){m(`wasm streaming compile failed: ${f}`),m("falling back to ArrayBuffer instantiation")}return xa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Aa)return Aa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ba=a=>{for(;0<a.length;)a.shift()(h)},Ca=[],Da=[],Ea=()=>{var a=h.preRun.shift();Da.unshift(a)},Fa=h.noExitRuntime||!0,Ga=0,C={},Ha=a=>{a instanceof za||"unwind"==a||ha(1,a)},Ia=a=>{oa=a;Fa||0<Ga||(h.onExit?.(a),p=!0);ha(a,new za(a))},Ja=a=>{oa=a;Ia(a)},Ka=()=>{if(!(Fa||0<Ga))try{var a=oa;oa=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!p)try{a(),Ka()}catch(b){Ha(b)}},Sa=(a,b)=>{Ma=a;Na=b;if(D)if(Oa||=!0,0==a)F=function(){setTimeout(G,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)F=function(){Qa(G)};
else if(2==a){if("undefined"==typeof Ra)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ra=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ra=setImmediate;F=function(){Ra(G)}}},ab=(a,b,c,d,e)=>{function g(){return f<Ta?(Ka(),!1):!0}D=a;Ua=d;var f=Ta;Oa=
!1;G=function(){if(!p)if(0<Va.length){var l=Va.shift();l.dd(l.Tc);if(Wa){var n=Wa,q=0==n%1?n-1:Math.floor(n);Wa=l.Vc?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Wa??0,q=Xa.$c??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(G,0)}else if(g())if(Ya=Ya+1|0,1==Ma&&1<Na&&0!=Ya%Na)F();else{0==Ma&&(Pa=performance.now());a:if(!p){for(l of Za)if(!1===l())break a;La(a);for(n of $a)n()}g()&&F()}};e||(0<b?Sa(0,1E3/b):
Sa(1,1),F());if(c)throw"unwind";},Oa=!1,F=null,Ta=0,D=null,Ua=0,Ma=0,Na=0,Ya=0,Va=[],Za=[],$a=[];function bb(){F=null;Ta++}var H=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===H)H=b+1E3/60;else for(;b+2>=H;)H+=1E3/60;setTimeout(a,Math.max(H-b,0))}}var Xa={},Pa,G,Ra,Wa;function cb(a){var b=I.Xb[a];b.target.removeEventListener(b.Wb,b.Bc,b.Yb);I.Xb.splice(a,1)}
function db(){if(navigator.userActivation?navigator.userActivation.isActive:I.oc&&I.Oc.mc){var a=I.bc;I.bc=[];for(var b of a)b.rc(...b.xc)}}function J(a){if(!a.target)return-4;if(a.Zb)a.Bc=function(c){++I.oc;I.Oc=a;db();a.$b(c);db();--I.oc},a.target.addEventListener(a.Wb,a.Bc,a.Yb),I.Xb.push(a);else for(var b=0;b<I.Xb.length;++b)I.Xb[b].target==a.target&&I.Xb[b].Wb==a.Wb&&cb(b--);return 0}function eb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={Uc:0,ed:0,pc:0,lc:0,vc:0,tc:0,nc:0,Yc:0,ld:0,Xc:0,cd:0,qc:0,ud:0,sc:0,hd(a,b,c){r.set(r.subarray(b,b+c),a)},nd(){for(;I.Xb.length;)cb(I.Xb.length-1);I.bc=[]},oc:0,bc:[],Wc(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of I.bc)if(e.rc==a&&d(e.xc,c))return;I.bc.push({rc:a,Fc:b,xc:c});I.bc.sort((g,f)=>g.Fc<f.Fc)},pd(a){I.bc=I.bc.filter(b=>b.rc!=a)},Xb:[],od:(a,b)=>{for(var c=0;c<I.Xb.length;++c)I.Xb[c].target!=a||b&&b!=I.Xb[c].Wb||
cb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?z(u,a):"":a;return fb[a]||("undefined"!=typeof document?document.querySelector(a):null)},gb=a=>0>fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},L,M=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);
f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},hb=(a,b,c,d,e,g)=>{I.nc||(I.nc=N(256));a={target:K(a),Wb:g,Zb:d,$b:(f=event)=>{var l=f.target.id?f.target.id:"",n=I.nc;M(eb(f.target),n+0,128);M(l,n+128,128);L.get(d)(e,n,b)&&f.preventDefault()},Yb:c};return J(a)},ib=(a,b,c,
d,e,g)=>{I.pc||(I.pc=N(160));a={target:K(a),Wb:g,Zb:d,$b:f=>{var l=I.pc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L.get(d)(e,l,b)&&f.preventDefault()},Yb:c};return J(a)},jb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;
v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=gb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,g)=>{I.lc||(I.lc=N(64));a=K(a);return J({target:a,mc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Wb:g,Zb:d,$b:(f=event)=>{jb(I.lc,f,a);L.get(d)(e,I.lc,b)&&f.preventDefault()},Yb:c})},kb=(a,b,c,d,e)=>{I.qc||(I.qc=N(257));return J({target:a,Wb:e,Zb:d,
$b:(g=event)=>{var f=I.qc,l=document.pointerLockElement||document.ac||document.hc||document.fc;r[f]=!!l;var n=l?.id||"";M(eb(l),f+1,128);M(n,f+129,128);L.get(d)(20,f,b)&&g.preventDefault()},Yb:c})},lb=(a,b,c,d,e)=>J({target:a,Wb:e,Zb:d,$b:(g=event)=>{L.get(d)(38,0,b)&&g.preventDefault()},Yb:c}),mb=(a,b,c,d)=>{I.tc||(I.tc=N(36));a=K(a);return J({target:a,Wb:"resize",Zb:d,$b:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=I.tc;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+
12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;L.get(d)(10,f,b)&&e.preventDefault()}}},Yb:c})},nb=(a,b,c,d,e,g)=>{I.sc||(I.sc=N(1552));a=K(a);return J({target:a,mc:"touchstart"==g||"touchend"==g,Wb:g,Zb:d,$b:f=>{var l={},n=f.touches;for(var q of n)q.Cc=q.Ec=0,l[q.identifier]=q;for(var t of f.changedTouches)t.Cc=1,l[t.identifier]=t;for(var qa of f.targetTouches)l[qa.identifier].Ec=1;n=I.sc;y[n>>3]=f.timeStamp;
r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;t=gb(a);qa=0;for(let E of Object.values(l))if(l=q>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,r[q+28]=E.Cc,r[q+29]=E.Ec,v[l+8]=E.clientX-(t.left|0),v[l+9]=E.clientY-(t.top|0),q+=48,31<++qa)break;v[n+8>>2]=qa;L.get(d)(e,n,b)&&f.preventDefault()},Yb:c})},P,ob=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},pb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},rb=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},sb=1,Q=[],R=[],tb=[],ub=[],vb=[],S=[],wb=[],xb=[],T=[],yb={},zb=4,Ab=0,Bb=a=>{for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b},Cb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=P[c](),f=g&&Bb(d);g?(g.name=f,d[f]=g):U||=1282;v[b+4*e>>2]=f}},Eb=(a,b)=>{a.ac||(a.ac=a.getContext,a.getContext=function(d,e){e=a.ac(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Dc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Db(c,b):0},Db=(a,b)=>{var c=Bb(xb),d={handle:c,attributes:b,version:b.Dc,wc:a};a.canvas&&(a.canvas.Sc=d);xb[c]=d;("undefined"==typeof b.Ac||b.Ac)&&Fb(d);return c},Fb=a=>{a||=V;if(!a.Rc){a.Rc=!0;var b=a.wc;b.kd=b.getExtension("WEBGL_multi_draw");b.bd=b.getExtension("EXT_polygon_offset_clamp");b.ad=b.getExtension("EXT_clip_control");b.vd=b.getExtension("WEBGL_polygon_mode");ob(b);pb(b);qb(b);b.Zc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.gd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.zc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.zc)b.zc=b.getExtension("EXT_disjoint_timer_query");rb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Gb=(a,b,c,d,e,g)=>{a={target:K(a),Wb:g,Zb:d,$b:(f=event)=>{L.get(d)(e,0,b)&&f.preventDefault()},Yb:c};J(a)},Hb=(a,b,c,d)=>{I.vc||(I.vc=N(96));return J({target:a,mc:!0,Wb:"wheel",Zb:d,$b:(e=event)=>{var g=I.vc;jb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>
3]=e.deltaZ;v[g+88>>2]=e.deltaMode;L.get(d)(9,g,b)&&e.preventDefault()},Yb:c})},Ib=["default","low-power","high-performance"],Jb=[null,[],[]],Kb=()=>{var a=rb(P);return a=a.concat(a.map(b=>"GL_"+b))},Lb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Kb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:
0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||
d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},Mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Nb=a=>{var b=Mb(a)+1,c=N(b);c&&M(a,c,b);return c},Ob=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Pb=[],Qb=a=>{a-=5120;return 0==a?r:1==a?u:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:ra},W=a=>{var b=P.Pc;if(b){var c=b.ec[a];"number"==typeof c&&(b.ec[a]=c=P.getUniformLocation(b,b.Mc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Rb=[],Sb=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Tb=a=>{(Tb=Sb())(a)},Vb=a=>{var b=Mb(a)+
1,c=Ub(b);M(a,c,b);return c},Yb=a=>{var b=Wb();a();Xb(b)};h.requestAnimationFrame=Qa;h.pauseMainLoop=bb;h.resumeMainLoop=function(){Ta++;var a=Ma,b=Na,c=D;D=null;ab(c,0,!1,Ua,!0);Sa(a,b);F()};h.preMainLoop&&Za.push(h.preMainLoop);h.postMainLoop&&$a.push(h.postMainLoop);for(var Y=0;32>Y;++Y)Pb.push(Array(Y));var Zb=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=Zb.subarray(0,Y);var $b=new Int32Array(288);for(Y=0;288>=Y;++Y)Rb[Y]=$b.subarray(0,Y);
var gc={Na:()=>ua(""),bb:()=>{Fa=!1;Ga=0},cb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];La(()=>ac(a,performance.now()))},b);C[a]={id:c,td:b};return 0},Ta:()=>{bb();D=null},I:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,S:(a,b,c)=>{a=K(a);if(!a)return-4;a=gb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},fa:()=>performance.now(),Ua:()=>performance.now(),Xa:(a,b)=>{function c(d){L.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Pa:()=>{ua("OOM")},db:a=>{var b=Error().stack.toString().split("\n");"Error"==b[0]&&b.shift();a=b[a+3];var c;return(c=/\bwasm-function\[\d+\]:(0x[0-9a-f]+)/.exec(a))?+c[1]:(c=/\bwasm-function\[(\d+)\]:(\d+)/.exec(a))?sa.ac[+c[1]]+ +c[2]:(c=/:(\d+):\d+(?:\)|$)/.exec(a))?2147483648|+c[1]:0},M:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),G:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),X:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),V:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),
W:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),Ya:(a,b,c)=>{a=L.get(a);ab(a,b,c)},y:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),ba:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),ea:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ac||document.body.hc||document.body.fc))return-1;a=K(a);if(!a)return-4;kb(a,b,c,d,"mozpointerlockchange");kb(a,b,c,d,"webkitpointerlockchange");
kb(a,b,c,d,"mspointerlockchange");return kb(a,b,c,d,"pointerlockchange")},O:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.ac||document.body.hc||document.body.fc))return-1;a=K(a);if(!a)return-4;lb(a,b,c,d,"mozpointerlockerror");lb(a,b,c,d,"webkitpointerlockerror");lb(a,b,c,d,"mspointerlockerror");return lb(a,b,c,d,"pointerlockerror")},K:(a,b,c,d)=>mb(a,b,c,d),Q:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),T:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),
U:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{Gb(a,b,c,d,31,"webglcontextlost");return 0},J:(a,b,c,d)=>{Gb(a,b,c,d,32,"webglcontextrestored");return 0},Y:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Hb(a,b,c,d):-1:-4,Ba:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Ib[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Dc:v[c+4],jd:v[c+5],Ac:r[b+24],Qc:r[b+25],md:v[c+7],qd:r[b+
32]};a=K(a);return!a||b.Qc?0:Eb(a,b)},qa:a=>{V=xb[a];h.ctx=P=V?.wc;return!a||P?0:-5},Oa:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=u[f+n],t=Jb[a];0===q||10===q?((1===a?la:m)(z(t)),t.length=0):t.push(q)}e+=l}w[d>>2]=e;return 0},r:a=>P.activeTexture(a),o:(a,b)=>{P.attachShader(R[a],S[b])},a:(a,b)=>{35051==a?P.yc=b:35052==a&&(P.dc=b);P.bindBuffer(a,Q[b])},s:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},i:(a,b)=>{P.bindFramebuffer(a,tb[b])},Ca:(a,b)=>{P.bindRenderbuffer(a,
ub[b])},q:(a,b)=>{P.bindSampler(a,T[b])},f:(a,b)=>{P.bindTexture(a,vb[b])},H:a=>{P.bindVertexArray(wb[a])},u:(a,b,c,d)=>P.blendColor(a,b,c,d),v:(a,b)=>P.blendEquationSeparate(a,b),w:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),nb:(a,b,c,d,e,g,f,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,g,f,l,n,q),Ea:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,u,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?u.subarray(c,c+b):b,d)},E:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,u,d,c):P.bufferSubData(a,b,u.subarray(d,d+c))},
ja:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),z:(a,b,c)=>{P.clearBufferfv(a,b,x,c>>2)},ia:(a,b,c)=>{P.clearBufferiv(a,b,v,c>>2)},h:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},gb:a=>{P.compileShader(S[a])},ua:(a,b,c,d,e,g,f,l)=>{2<=V.version?P.dc||!f?P.compressedTexImage2D(a,b,c,d,e,g,f,l):P.compressedTexImage2D(a,b,c,d,e,g,u,l,f):P.compressedTexImage2D(a,b,c,d,e,g,u.subarray(l,l+f))},wa:(a,b,c,d,e,g,f,l,n)=>{P.dc?P.compressedTexImage3D(a,b,c,d,e,g,f,l,n):P.compressedTexImage3D(a,b,c,d,e,g,f,u,n,l)},pa:()=>
{var a=Bb(R),b=P.createProgram();b.name=a;b.kc=b.ic=b.jc=0;b.uc=1;R[a]=b;return a},ib:a=>{var b=Bb(S);S[b]=P.createShader(a);return b},t:a=>P.cullFace(a),jb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.yc&&(P.yc=0),d==P.dc&&(P.dc=0))}},F:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=tb[d];e&&(P.deleteFramebuffer(e),e.name=0,tb[d]=null)}},j:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=
v[b+4*c>>2],e=ub[d];e&&(P.deleteRenderbuffer(e),e.name=0,ub[d]=null)}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},g:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=vb[d];e&&(P.deleteTexture(e),e.name=0,vb[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];P.deleteVertexArray(wb[d]);wb[d]=null}},m:a=>P.depthFunc(a),n:a=>{P.depthMask(!!a)},c:a=>P.disable(a),ca:a=>
{P.disableVertexAttribArray(a)},pb:(a,b,c)=>{P.drawArrays(a,b,c)},qb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},sb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},rb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},e:a=>P.enable(a),Cb:a=>{P.enableVertexAttribArray(a)},da:a=>P.frontFace(a),Fa:(a,b)=>{Cb(a,b,"createBuffer",Q)},Da:(a,b)=>{Cb(a,b,"createRenderbuffer",ub)},ra:(a,b)=>{Cb(a,b,"createSampler",T)},za:(a,b)=>{Cb(a,b,"createTexture",vb)},La:(a,b)=>{Cb(a,b,"createVertexArray",wb)},ma:(a,b)=>P.getAttribLocation(R[a],
b?z(u,b):""),b:(a,b)=>Lb(a,b),oa:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},B:(a,b,c)=>{if(c)if(a>=sb)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.kc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.kc=Math.max(a.kc,P.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.kc}else if(35722==b){if(!a.ic)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.ic=
Math.max(a.ic,P.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.ic}else if(35381==b){if(!a.jc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.jc=Math.max(a.jc,P.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.jc}else v[c>>2]=P.getProgramParameter(a,b);else U||=1281},fb:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},_:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),
v[c>>2]=a?a.length+1:0):v[c>>2]=P.getShaderParameter(S[a],b):U||=1281},Ma:(a,b)=>{if(2>V.version)return U||=1282,0;var c=yb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Kb().map(Nb),c=yb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},A:(a,b)=>{b=b?z(u,b):"";if(a=R[a]){var c=a,d=c.ec,e=c.Nc,g;if(!d){c.ec=d={};c.Mc={};var f=P.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=P.getActiveUniform(c,g);var n=l.name;l=l.size;var q=Ob(n);q=0<q?n.slice(0,
q):n;var t=c.uc;c.uc+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.Mc[t++]=q}}c=a.ec;d=0;e=b;g=Ob(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Nc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},mb:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];P.invalidateFramebuffer(a,d)},C:a=>{a=R[a];P.linkProgram(a);a.ec=0;a.Nc={}},Ka:(a,b)=>{3317==a?zb=b:3314==a&&(Ab=b);P.pixelStorei(a,b)},x:(a,b)=>P.polygonOffset(a,b),ob:a=>P.readBuffer(a),Aa:(a,
b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),D:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},d:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},ka:(a,b,c,d)=>P.scissor(a,b,c,d),hb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?z(u,f,d?w[d+4*g>>2]:void 0):"";e+=f}P.shaderSource(S[a],e)},lb:(a,b,c)=>P.stencilFunc(a,b,c),ha:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),l:a=>P.stencilMask(a),kb:(a,b,c)=>P.stencilOp(a,b,c),ga:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),ta:(a,b,c,d,e,g,f,l,n)=>{if(2<=
V.version){if(P.dc){P.texImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var q=Qb(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,g,f,l,q,n);return}}if(n){q=Qb(l);var t=e*((Ab||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+zb-1&-zb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,e,g,f,l,n)},va:(a,b,c,d,e,g,f,l,n,q)=>{if(P.dc)P.texImage3D(a,b,c,d,e,g,f,l,n,q);
else if(q){var t=Qb(n);P.texImage3D(a,b,c,d,e,g,f,l,n,t,q>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,g,f,l,n,null)},ya:(a,b,c)=>P.texParameteri(a,b,c),sa:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),xa:(a,b,c,d,e,g)=>P.texStorage3D(a,b,c,d,e,g),Bb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},na:(a,b)=>{P.uniform1i(W(a),b)},xb:(a,b,c)=>{if(2<=V.version)b&&
P.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Rb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},Ab:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},wb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Rb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=
v.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},zb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},vb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Rb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),
d)}},yb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Rb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),
d)}},tb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=R[a];P.useProgram(a);P.Pc=a},Db:(a,
b)=>{P.vertexAttribDivisor(a,b)},Eb:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,b,c,d,e)},Fb:(a,b,c,d,e,g)=>{P.vertexAttribPointer(a,b,c,!!d,e,g)},la:(a,b,c,d)=>P.viewport(a,b,c,d),ab:Ia,eb:(a,b)=>{Tb(u.subarray(a,a+b));return 0},$a:function(){h.Gc=a=>{0!=bc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Gc)},_a:function(){h.Lc=a=>{const b=a.clipboardData.getData("text");Yb(()=>{const c=Vb(b);cc(c)})};window.addEventListener("paste",h.Lc)},Za:function(){h.rd=[];h.Hc=
b=>{b.stopPropagation();b.preventDefault()};h.Ic=b=>{b.stopPropagation();b.preventDefault()};h.Jc=b=>{b.stopPropagation();b.preventDefault()};h.Kc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.sd=c;dc(c.length);for(let e=0;e<c.length;e++)Yb(()=>{const g=Vb(c[e].name);ec(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);fc(b.clientX,b.clientY,d)};const a=h.cc;a.addEventListener("dragenter",h.Hc,!1);a.addEventListener("dragleave",h.Ic,
!1);a.addEventListener("dragover",h.Jc,!1);a.addEventListener("drop",h.Kc,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Gb:function(a,b){0!==b&&(document.title=b?z(u,b):"");a=a?z(u,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?fb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.cc=K(a);h.cc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.cc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Sa:function(){window.removeEventListener("beforeunload",h.Gc)},Ra:function(){window.removeEventListener("paste",h.Lc)},Qa:function(){const a=h.cc;a.removeEventListener("dragenter",h.Hc);a.removeEventListener("dragleave",h.Ic);a.removeEventListener("dragover",h.Jc);a.removeEventListener("drop",h.Kc)},p:function(){h.cc&&h.cc.requestPointerLock&&h.cc.requestPointerLock()},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,
b);g.data.set(u.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Z:function(a,b){b=b?z(u,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Hb;c=na.buffer;h.HEAP8=r=new Int8Array(c);h.HEAP16=pa=new Int16Array(c);h.HEAPU8=u=new Uint8Array(c);h.HEAPU16=ra=new Uint16Array(c);h.HEAP32=v=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);h.HEAPF32=x=new Float32Array(c);h.HEAPF64=y=new Float64Array(c);h.HEAP64=new BigInt64Array(c);h.HEAPU64=new BigUint64Array(c);L=Z.Vb;A--;h.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return Z}A++;h.monitorRunDependencies?.(A);var b={a:gc};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});va??=h.locateFile?h.locateFile("zigtris.wasm",k):k+"zigtris.wasm";return a((await ya(b)).instance)})();
var hc=h._main=(a,b)=>(hc=h._main=Z.Jb)(a,b),cc=h.__sapp_emsc_onpaste=a=>(cc=h.__sapp_emsc_onpaste=Z.Kb)(a),bc=h.__sapp_html5_get_ask_leave_site=()=>(bc=h.__sapp_html5_get_ask_leave_site=Z.Lb)(),dc=h.__sapp_emsc_begin_drop=a=>(dc=h.__sapp_emsc_begin_drop=Z.Mb)(a),ec=h.__sapp_emsc_drop=(a,b)=>(ec=h.__sapp_emsc_drop=Z.Nb)(a,b),fc=h.__sapp_emsc_end_drop=(a,b,c)=>(fc=h.__sapp_emsc_end_drop=Z.Ob)(a,b,c);
h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,l)=>(h.__sapp_emsc_invoke_fetch_cb=Z.Pb)(a,b,c,d,e,g,f,l);var ac=(a,b)=>(ac=Z.Qb)(a,b),N=a=>(N=Z.Rb)(a),Xb=a=>(Xb=Z.Sb)(a),Ub=a=>(Ub=Z.Tb)(a),Wb=()=>(Wb=Z.Ub)();function ic(a=[]){var b=hc;a.unshift(fa);var c=a.length,d=Ub(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Vb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ja(g)}catch(f){Ha(f)}}
function jc(a=ea){function b(){h.calledRun=!0;if(!p){Z.Ib();h.onRuntimeInitialized?.();h.noInitialRun||ic(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ca.unshift(c)}Ba(Ca)}}if(0<A)B=jc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ea();Ba(Da);0<A?B=jc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();jc();
